controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:216026633254:certificate/4a247bd6-77c4-4eca-bda3-cd9660c02c72"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    targetPorts:
      https: http   # ELB terminates TLS; forward decrypted HTTP to nginx's port 80
